#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveior,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
	return;
}


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);

		if(joystick.joy1_y1 > -15 && joystick.joy1_y1 < 15)
		{
			motor[leftDrive] = 0;
		}
		else
		{
			motor[leftDrive] = joystick.joy1_y1*0.5;
		}
		if(joystick.joy1_y2 > -15 && joystick.joy1_y2 < 15)
		{
			motor[rightDrive] = 0;
		}
		else
		{
			motor[rightDrive] = joystick.joy1_y2*0.5;
		}


		if(joy2Btn(6) == 1)
		{
			motor[harvester] = 100;
		}
		if(joy2Btn(6) == 0);
		{
			motor[harvester] = 0;
		}
		if(joy2Btn(8) == 1)
		{
			motor[harvester] = 50;
		}
		if(joy2Btn(8) == 0)
		{
			motor[harvester] = 0;
		}
		if(joy2Btn(7) == 1)
		{
			motor[[conveior] = 100;
		}
		if(joy2Btn(7) == 0)
		{
			motor[conveior] = 0;
		}
		if(joy2Btn(9) == 1)
		{
			motor[conveior] = 65;
		}
		if(joy2Btn(7) == 0)
		{
			motor[conveior] = 0;
		}


	}
}
